// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7QtibSiFtlH-FDRW4vnlYBMpPTlTOiMI',
    appId: '1:706913486829:web:80b16e31454e9f691109e4',
    messagingSenderId: '706913486829',
    projectId: 'aula10-db',
    authDomain: 'aula10-db.firebaseapp.com',
    storageBucket: 'aula10-db.firebasestorage.app',
    measurementId: 'G-PP61CT5HW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArIix3cwAO269UmGrEV6OC9Nhz7TQC8nk',
    appId: '1:706913486829:android:07ee159499b81faf1109e4',
    messagingSenderId: '706913486829',
    projectId: 'aula10-db',
    storageBucket: 'aula10-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq1J1rShV8K7y063fKUPeCQb-JWL75t7w',
    appId: '1:706913486829:ios:3169cad4808a40521109e4',
    messagingSenderId: '706913486829',
    projectId: 'aula10-db',
    storageBucket: 'aula10-db.firebasestorage.app',
    iosBundleId: 'com.example.exdb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq1J1rShV8K7y063fKUPeCQb-JWL75t7w',
    appId: '1:706913486829:ios:3169cad4808a40521109e4',
    messagingSenderId: '706913486829',
    projectId: 'aula10-db',
    storageBucket: 'aula10-db.firebasestorage.app',
    iosBundleId: 'com.example.exdb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7QtibSiFtlH-FDRW4vnlYBMpPTlTOiMI',
    appId: '1:706913486829:web:97bfaa48e2b5cab51109e4',
    messagingSenderId: '706913486829',
    projectId: 'aula10-db',
    authDomain: 'aula10-db.firebaseapp.com',
    storageBucket: 'aula10-db.firebasestorage.app',
    measurementId: 'G-M6XQWT92JN',
  );
}
